config/routes.rb
 ControleDeEstoque::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :admin do
    resources :clientes do
      resources :servicos
      resources :tarefas
      
    end
  end

  match '/signin',  to: 'sessions#new',            via: 'get'
  match '/signout',  to: 'sessions#destroy',            via: 'delete'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/cadastrar',  to: 'users#new',            via: 'get'
  match '/ajuda',    to: 'static_pages#ajuda',    via: 'get'
  match '/sobre',   to: 'static_pages#sobre',   via: 'get'
  match '/contato', to: 'static_pages#contato', via: 'get'
  match '/agendamentos/seleciona_horarios', to: 'agendamentos#seleciona_horarios', via: 'get'
  match '/agendamentos/seleciona_horarios2', to: 'agendamentos#seleciona_horarios2', via: 'get'
  match '/seleciona_medico', to: 'medicos#seleciona_medico', via: 'get'
  match '/agendamentos/lista_agendamentos_ajax', to: 'agendamentos#lista_agendamentos_ajax', via: 'get'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :agendamentos
  resources :pacientes
  resources :medicos
  resources :clientes

  get "static_pages/home"
  get "static_pages/ajuda"
  
  root "admin/clientes#index"  
  

  

  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def ajuda
  end

  def contato
  end

  def sobre
  end
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/ajuda.html.erb
<% provide(:title, 'Ajuda') %>
<h1>Ajuda</h1>
<p>Ajuda</p>

app/views/static_pages/home.html.erb
<!-- <div class="center hero-unit"> -->
<div class="container">
	<div class="container">
		<div class="center jumbotron">
			<h1>Agendamento Médico</h1>
			<h2>Acesse o sistema, com seu usuário e senha, para fazer agendamentos</h2> 

	

	<!-- <%= link_to "Cadastre-se!", cadastrar_path, class: "btn btn-large btn-primary" %> -->
			<%= link_to "Acessar", signin_path, class: "btn btn-lg btn-primary" %>
		</div>
	</div>
</div>