config/routes.rb
 ControleDeEstoque::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :admin do
    resources :clientes do
      resources :servicos
      resources :tarefas
      
    end
  end

  match '/signin',  to: 'sessions#new',            via: 'get'
  match '/signout',  to: 'sessions#destroy',            via: 'delete'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/cadastrar',  to: 'users#new',            via: 'get'
  match '/ajuda',    to: 'static_pages#ajuda',    via: 'get'
  match '/sobre',   to: 'static_pages#sobre',   via: 'get'
  match '/contato', to: 'static_pages#contato', via: 'get'
  match '/agendamentos/seleciona_horarios', to: 'agendamentos#seleciona_horarios', via: 'get'
  match '/agendamentos/seleciona_horarios2', to: 'agendamentos#seleciona_horarios2', via: 'get'
  match '/seleciona_medico', to: 'medicos#seleciona_medico', via: 'get'
  match '/agendamentos/lista_agendamentos_ajax', to: 'agendamentos#lista_agendamentos_ajax', via: 'get'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :agendamentos
  resources :pacientes
  resources :medicos
  resources :clientes

  get "static_pages/home"
  get "static_pages/ajuda"
  
  root "admin/clientes#index"  
  

  

  

end

app/models/paciente.rb
# == Schema Information
#
# Table name: pacientes
#
#  id         :integer         not null, primary key
#  nome       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Paciente < ActiveRecord::Base
	has_many	:agendamentos
	has_many 	:medicos, through: :agendamentos

	validates 	:nome, presence: true
end

app/controllers/pacientes_controller.rb
class PacientesController < ApplicationController
	def new
		@paciente=Paciente.new()
	end

	def create
		@paciente=Paciente.new(paciente_params)
		if @paciente.save
			flash[:success]="Paciente incluido com sucesso"
			redirect_to paciente_path(@paciente)
		else
			flash[:error]="Erro ao salvar paciente"
		end
	end

	def paciente_params
		params.require(:paciente).permit(:nome)
	end

	def index
		@pacientes=Paciente.all()
	end

end

app/helpers/pacientes_helper.rb
module PacientesHelper
end

app/views/pacientes/index.html.erb
<!-- <div class="container"> -->
<h1>Pacientes</h1>



  <%= link_to 'Novo Paciente', new_paciente_path, class: "btn btn-medium btn-default" %>
<br>
<br>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Nome</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pacientes.each do |paciente| %>
      <tr>
        <td><%= link_to paciente.nome, paciente %></td>
        <!-- <td><%= link_to 'Exibir', paciente %></td> -->
        <td><%= link_to 'Novo Agendamento', controller: "medicos", action: 'seleciona_medico', paciente_id: paciente.id, paciente_nome: paciente.nome %></td>
        <td><%= link_to 'Editar', edit_paciente_path(paciente) %></td>
        <td><%= link_to 'Excluir', paciente, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<!-- </div> -->

app/views/pacientes/new.html.erb
<%= form_for(@paciente) do |f| %>
<%= f.label :Paciente, "Nome do Paciente" %>
<%= f.text_field :nome %>
<%= f.submit "Incluir Paciente", :class =>"btn btn-medium btn-primary" %>
<% end %>