config/routes.rb
 ControleDeEstoque::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  namespace :admin do
    resources :clientes do
      resources :servicos
      resources :tarefas
      
    end
  end

  match '/signin',  to: 'sessions#new',            via: 'get'
  match '/signout',  to: 'sessions#destroy',            via: 'delete'
  match '/signup',  to: 'users#new',            via: 'get'
  match '/cadastrar',  to: 'users#new',            via: 'get'
  match '/ajuda',    to: 'static_pages#ajuda',    via: 'get'
  match '/sobre',   to: 'static_pages#sobre',   via: 'get'
  match '/contato', to: 'static_pages#contato', via: 'get'
  match '/agendamentos/seleciona_horarios', to: 'agendamentos#seleciona_horarios', via: 'get'
  match '/agendamentos/seleciona_horarios2', to: 'agendamentos#seleciona_horarios2', via: 'get'
  match '/seleciona_medico', to: 'medicos#seleciona_medico', via: 'get'
  match '/agendamentos/lista_agendamentos_ajax', to: 'agendamentos#lista_agendamentos_ajax', via: 'get'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :agendamentos
  resources :pacientes
  resources :medicos
  resources :clientes

  get "static_pages/home"
  get "static_pages/ajuda"
  
  root "admin/clientes#index"  
  

  

  

end

app/models/medico.rb
# == Schema Information
#
# Table name: medicos
#
#  id         :integer         not null, primary key
#  nome       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Medico < ActiveRecord::Base
	has_many	:agendamentos
	has_many	:pacientes, through: :agendamentos

	validates 	:nome, presence: true
end

app/controllers/medicos_controller.rb
class MedicosController < ApplicationController
	def seleciona_medico
		@paciente_id = params[:paciente_id]
		@paciente_nome = params[:paciente_nome]

		@medicos = Medico.all

	end

	def index
		@medicos = Medico.all
	end

	def show
		@medico = Medico.find(params[:id])
	end


	def new
		@medico = Medico.new
	end

	def create
		@medico=Medico.new(medico_params)
		if @medico.save
			flash[:success]="Médico incluido com sucesso"
			redirect_to medico_path(@medico)
		else
			flash[:error]="Erro ao salvar médico"
		end
	end

	def medico_params
		params.require(:medico).permit(:nome)
	end


end

app/helpers/medicos_helper.rb
module MedicosHelper
end

app/views/medicos/index.html.erb
<!-- <div class="container"> -->
<h1>Médicos</h1>



  <%= link_to 'Cadastrar Médico', new_medico_path, class: "btn btn-medium btn-primary" %>
<br>
<br>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Nome</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @medicos.each do |medico| %>
      <tr>
        <td><%= link_to medico.nome, medico %></td>
        <!-- <td><%= link_to 'Exibir', medico %></td> -->
        <!-- <td><%#= link_to 'Novo Agendamento', controller: "medicos", action: 'seleciona_medico', paciente_id: medico.id, paciente_nome: medico.nome %></td> -->
        <td><%= link_to 'Novo Agendamento', controller: "agendamentos", action: "new", medico_id: medico.id  %></td>
        <td><%= link_to 'Editar', edit_medico_path(medico) %></td>
        <td><%= link_to 'Excluir', medico, method: :delete, data: { confirm: 'Tem certeza que deseja excluir o médico #{medico.nome}?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<!-- </div> -->


 

app/views/medicos/new.html.erb
<%= bootstrap_form_for @medico, layout: :horizontal do |f| %>
	<%= f.text_field :nome, label: "Nome do Médico" %>
	<%= f.form_group do %>
		<%= f.submit "Cadastrar Médico", :class =>"btn btn-medium btn-primary" %>
	<% end %>
<% end %>

app/views/medicos/seleciona_medico.html.erb
<div class="container">
		<form id="form_seleciona_medico" method="get" class="form-horizontal" role="form" action="/agendamentos/seleciona_horarios">
			<%= hidden_field_tag :authenticiy_token, form_authenticity_token %>
			<div class="form-group">
				<label class="control-label col-md-2">Paciente:</label>
				<div class="col-md-10">
					
					<input type="hidden" name="paciente_id" value=<%= @paciente_id %> />
					<p class="form-control-static"><%= @paciente_nome %></p>
				</div>
				
				<label class="control-label col-md-2">Médico:</label>
				<div class="col-md-10">
				
					<select class="form-control" id="select_seleciona_medico" name="medico_id"  required>
						<option value="">--- Selecione um médico ---</option>

						<%= @medicos.each do |medico| %>
							<option value=<%= medico.id %> > <%=medico.nome %> </option>
						<% end %>
						
					</select>
				</div>
			</div>
			<div class="form-group">
				<div class="col-md-10 col-md-offset-2"> 

					<button type="submit" class="btn btn-primary">Avançar</button>
				</div> 
			</div>
		</form>
	</div>
	<script src="/assets/valida_select_medico.js" ></script>
	

app/views/medicos/show.html.erb
<% provide(:title, @medico.nome) %>
<div class="row">
  <aside class="col-md-4">
    <section>
    	<h1>
        	<% ## gravatar_for @medico.nome %>
        	<%= @medico.nome %>
      	</h1>
      	<%= link_to "Novo Agendamento", new_agendamento_path, class: "btn btn-primary" %>



    </section>
  </aside>
</div>